// <auto-generated />
using System;
using DomenicaEscobar_ExamenP1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DomenicaEscobar_ExamenP1.Migrations
{
    [DbContext(typeof(DomenicaEscobar_ExamenP1Context))]
    [Migration("20231025132607_DomenicaEscobar_DB")]
    partial class DomenicaEscobar_DB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DomenicaEscobar_ExamenP1.Models.DomenicaEscobar_Tabla", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("DEConTocino")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DEFecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("DENombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DEPrecio")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("DomenicaEscobar_Tabla");
                });
#pragma warning restore 612, 618
        }
    }
}
